added section01
OlegAdamovich/landing01 pull request #1
Opened 2021-03-01 13:13 UTC by OlegAdamovich

2021-03-01 13:45 UTC, mhryshkin requested changes

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +    <section class="section1">
@OlegAdamovich When you add new sections, is it gonna be `section 2`, `section 3`, `section 4` etc.? If I ask you then to change the order of section, what happens?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +        <div class="container">
@OlegAdamovich Do you need an extra `div` element here? Look here - https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%B8%D0%BA%D1%81

any conclusions?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +                <div class="section1__text_regular-gray">
Is this the only place in the whole document you will have `text_regular-gray`? How are you gonna reuse it? Using `section1__text_regular-gray`?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +                <button class="section1__button">More Info</button>
Same as above - `section1__button` I hardly believe this the only button in the whole document, how will you reuse the button styles?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +<div class="wrapper">
Is it necessary to have here an extra div?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +    <link rel="stylesheet" href="../style.css">
Do you connect styles twice?

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +            <div class="nav__item">Home</div>
Are you it has to be a div? I think you will need some anchors later

2021-03-01 13:45 UTC, mhryshkin commented on index.html
> +                <img src="images/phone.png" alt="image">
`alt=image` looks really 'helpful', especially if a user doesn't see an image

2021-03-01 15:45 UTC, OlegAdamovich commented on index.html
> +                <img src="images/phone.png" alt="image">
Rename attribute alt that helps to understanding the content.

2021-03-01 15:51 UTC, OlegAdamovich commented on index.html
> +            <div class="nav__item">Home</div>
Changed `div` to tag `a`.

2021-03-01 15:54 UTC, OlegAdamovich commented on index.html
> +    <link rel="stylesheet" href="../style.css">
Extra link removed.

2021-03-01 15:59 UTC, OlegAdamovich commented on index.html
> +<div class="wrapper">
I don't understand why this div is extra. It sets the width and position of the document.

2021-03-01 16:08 UTC, OlegAdamovich commented on index.html
> +                <button class="section1__button">More Info</button>
Changed it in independent page component that can be reused.

2021-03-01 16:13 UTC, mhryshkin commented on index.html
> +<div class="wrapper">
@OlegAdamovich Doesn't the body tag work for you?

2021-03-01 16:26 UTC, OlegAdamovich commented on index.html
> +        <div class="container">
Got it. Extra div removed.

2021-03-01 16:26 UTC, OlegAdamovich commented on index.html
> +    <section class="section1">
Renamed.

2021-03-01 16:59 UTC, mhryshkin commented on index.html
> +                <img src="images/phone.png" alt="image">
@OlegAdamovich `alt` attribute is shown to a user, don't be shy to write in a more readable way like 'Phone image' and 'Logo icon'

2021-03-01 17:14 UTC, mhryshkin commented on index.html
> +            <div class="text-gray description_text">
What is `description_text`? It looks like a modifier

2021-03-01 18:06 UTC, OlegAdamovich commented on index.html
> +<div class="wrapper">
Wrapper removed. Add styles to `body`.

2021-03-01 18:10 UTC, OlegAdamovich commented on index.html
> +            <div class="text-gray description_text">
Converted in element.

2021-03-01 19:03 UTC, mhryshkin commented on index.html
> +            <div class="text-gray">
@OlegAdamovich Don't you find the name a bit [weird ](https://ru.bem.info/methodology/quick-start/#%D0%B1%D0%BB%D0%BE%D0%BA)for a block? Did you check If you need `text-gray` with this color and other styles elsewhere in the document?

2021-03-01 19:07 UTC, mhryshkin commented on index.html
> +<div class="wrapper">
@OlegAdamovich It's better to use classes everywhere possible, any thoughts on how to call a class for a body tag?

2021-03-01 20:39 UTC, OlegAdamovich commented on index.html
> +<div class="wrapper">
Added class to `body` tag.

2021-03-02 10:47 UTC, OlegAdamovich commented on index.html
> +<div class="wrapper">
Rename class to `page`.

2021-03-02 10:58 UTC, OlegAdamovich commented on index.html
> +                <div class="section1__text_regular-gray">
Redone as element `description__content-text`.

2021-03-02 10:59 UTC, OlegAdamovich commented on index.html
> +            <div class="text-gray">
Redone as element `description__content-text.`

2021-03-02 11:46 UTC, mhryshkin commented
👍

2021-03-02 11:47 UTC, merged